### ISSUE TITLE
Peerflix error

### ISSUE THREAD

**Issue by Ismail36** [mafintosh/peerflix#198]
C:\Users\Hamza>coffee Desktop\Webflix\app.coffee        <---- The file i wanna start
Error: Cannot find module 'peerflix'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (C:\Users\Hamza\Desktop\PiStream\Webflix\app.coffee:1:12)
  at Object.<anonymous> (C:\Users\Hamza\Desktop\PiStream\Webflix\app.coffee:1:1)
  at Module._compile (module.js:456:26)

**Comment by mafintosh** [comment]
Did you install peerflix as a dependency? Your error isn't really saying
else besides the fact that node can't find peerflix
