### ISSUE TITLE
Error while trying to load a magnet link 

### ISSUE THREAD

**Issue by jgalati** [mafintosh/peerflix#254]
I'm running:
OS: Windows 8.1
npm: v2.14.12
node: v4.2.4
peerflix 0.32.3

Every time I try to stream I get the same error message.

```
C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\node_modules\torrent-discovery\nod
e_modules\re-emitter\index.js:17
    source.on(event, listener)
           ^

TypeError: source.on is not a function
    at C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\node_modules\torrent-discovery\node_modules\re-emitter\index.js:17:12
    at Array.forEach (native)
    at reemit (C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\node_modules\torrent-discovery\node_modules\re-emitter\index.js:10:10)
    at new Discovery (C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\node_modules\torrent-discovery\index.js:42:5)
    at Discovery (C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\node_modules\torrent-discovery\index.js:16:44)
    at torrentStream (C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\index.js:110:19)
    at module.exports (C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\index.js:184:16)
    at ontorrent (C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\app.js:110:16)
    at C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\app.js:453:3
    at C:\Users\****\AppData\Roaming\npm\node_modules\peerflix\node_modules\parse-torrent\index.js:59:7
```

Thanks.

**Comment by diogoviannaaraujo** [comment]
+1

**Comment by sangshuduo** [comment]
+1

**Comment by hanhpho** [comment]
same issue

**Comment by guigaoliveira** [comment]
+1

**Comment by jaruba** [comment]
@feross :P

**Comment by feross** [comment]
Sorry folks :blush: This should be fixed now, if you reinstall peerflix.

**Comment by jgalati** [comment]
Fixed. ;)
