### ISSUE TITLE
blocklist Error: Invalid block range

### ISSUE THREAD

**Issue by tristan-k** [mafintosh/peerflix#261]
I'm using a pregenerated blocklist from https://github.com/walshie4/Ultimate-Blocklist, but peerflix is complaining about an `Invalid block range`. What's wrong with that list?

```
peerflix "magnet-link" --blocklist /Users/tristank/Downloads/blocklist.txt --vlc        
/usr/local/lib/node_modules/peerflix/node_modules/ip-set/index.js:130
		if (start < 0 || end > 4294967295 || end < start) throw new Error('Invalid block range')
		                                                  ^

Error: Invalid block range
    at Object.self.add (/usr/local/lib/node_modules/peerflix/node_modules/ip-set/index.js:130:59)
    at /usr/local/lib/node_modules/peerflix/node_modules/ip-set/index.js:144:9
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/peerflix/node_modules/ip-set/index.js:143:13)
    at torrentStream (/usr/local/lib/node_modules/peerflix/node_modules/torrent-stream/index.js:106:16)
    at module.exports (/usr/local/lib/node_modules/peerflix/index.js:186:16)
    at ontorrent (/usr/local/lib/node_modules/peerflix/app.js:110:16)
    at /usr/local/lib/node_modules/peerflix/app.js:453:3
    at /usr/local/lib/node_modules/peerflix/node_modules/dezalgo/dezalgo.js:17:12
    at RawTask.call (/usr/local/lib/node_modules/peerflix/node_modules/asap/asap.js:40:19)
```

**Comment by ckiikc** [comment]
I encounter the same problem and it result to be some row in the blocklist that were something like this one:
Malicious TCP PORT:443:1.192.128.23-1.192.128.23

which has two colons with a port number between it. Obviously there is a problem with the ip range regex

/^\s*[^#].*?\s*:\s*([a-f0-9.:]+?)\s*-\s*([a-f0-9.:]+?)\s*$/

that search for a colons for the ips range, but also search for colons for ipv6 range.
So what I suppose is that the string of the rows in the block list have not to contain colons in the range name.

I used a trick in the code in order to show which address give the error, modifying the file index.js in peerflix/node_modules/ip-set/ like that

    **var myStart=start;**
    if (typeof start !== 'number') start = ip.toLong(start)
    
    if (!end) end = start
    if (typeof end !== 'number') end = ip.toLong(end)

    **if (start < 0 || end > 4294967295 || end < start) {
      console.log('Invalid block range ' + myStart)

    }else{
      if (tree) tree.add(start, end)
      else tree = new IPSet(start, end)
    }**
