### ISSUE TITLE
[fixed] can't run updated peerflix@0.36.2 

### ISSUE THREAD

**Issue by selvodka** [mafintosh/peerflix#313]
When i run outputs this : 
/usr/local/lib/node_modules/peerflix/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:10
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/peerflix/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:10:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/peerflix/node_modules/simple-websocket/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)

Fixed by updating node.js via https://github.com/nodesource/distributions/#debinstall from 4.2.x to 6.x

**Comment by feross** [comment]
Sure thing. Just fixed!
