### ISSUE TITLE
error when i run peerflix

### ISSUE THREAD

**Issue by Joseph65** [mafintosh/peerflix#343]
I get this error when i open peerflix

/usr/local/lib/node_modules/peerflix/node_modules/parse-torrent/index.js:257
;(function () { Buffer.alloc(0) })()
                       ^

TypeError: Buffer.alloc is not a function
    at /usr/local/lib/node_modules/peerflix/node_modules/parse-torrent/index.js:257:24
    at Object.<anonymous> (/usr/local/lib/node_modules/peerflix/node_modules/parse-torrent/index.js:257:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/peerflix/app.js:14:20)
    at Module._compile (module.js:410:26)

im on ubuntu 16.04

**Comment by mafintosh** [comment]
looks like you are running a very old version of node. try upgrading to a newer one.
