### ISSUE TITLE
Cannot start peerflix. Reason getting Syntax Error. Ubuntu 16.04

### ISSUE THREAD

**Issue by masterplayer30** [mafintosh/peerflix#360]
To whom may concern:

I get this while trying to stream a torrent using your app:

chrx@chrx:~/Downloads$ peerflix "magnet:?xt=urn:btih:8969DCD3A935CC99BD3F01DF2931E05401BADBF6&dn=Swamp+People+S10E03+480p+x264-mSD+%5Beztv%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftorrent.gresille.org%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce" --vlc
/usr/lib/node_modules/peerflix/node_modules/inquirer/lib/prompts/list.js:32
      let index = _.findIndex(this.opt.choices.realChoices, ({ value }) => value === def);
                                                             ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Function.promptModule.restoreDefaultPrompts (/usr/lib/node_modules/peerflix/node_modules/inquirer/lib/inquirer.js:55:33)
    at Object.inquirer.createPromptModule (/usr/lib/node_modules/peerflix/node_modules/inquirer/lib/inquirer.js:65:16)
    at Object.<anonymous> (/usr/lib/node_modules/peerflix/node_modules/inquirer/lib/inquirer.js:77:28)

Can this be fixed?

Bobby Burgess

**Comment by masterplayer30** [comment]
Updating to nodejs 10 works!
