### ISSUE TITLE
os.tmpDir is not a function

### ISSUE THREAD

**Issue by QuAzI** [mafintosh/peerflix#374]
Can't run peerflix anymore after node reinstall
```
c:\Users\rusla\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\index.js:36
var TMP = fs.existsSync('/tmp') ? '/tmp' : os.tmpDir()
                                              ^

TypeError: os.tmpDir is not a function
    at Object.<anonymous> (c:\Users\rusla\AppData\Roaming\npm\node_modules\peerflix\node_modules\torrent-stream\index.js:36:47)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (c:\Users\rusla\AppData\Roaming\npm\node_modules\peerflix\index.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

peerflix@0.39.0
>npm --version
6.14.11
>node --version
v14.16.0

**Comment by QuAzI** [comment]
uhh, just `npm install -g peerflix` need after new node installed
